### ISSUE TITLE
Export also in the format IFCXML

### ISSUE THREAD

**Issue by klacol** [buildingSMART/IfcDoc#29]
Today I learned from Thomas Liebich, that we can download all IfcPropertySetTemplate and IfcPropertyTemplate as IFC file in the format step pyhsical file.

This can be done here:

http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/
then A. Computer interpretable listings
then A.1 General Usage
then Property and quantity templates
then IFC-SPF property and quantity templates

Directlink: 
http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/annex/annex-a/general-usage/IFC4_ADD2.ifc

This is really great; all the template in all languages in one file; and the GUID's are identical to the GUID's in bSDD. A huge step foreward; congrats.

Now my request: Could you also provide a download in the format IFCXML?

**Comment by timchipman** [comment]
It's now possible to export IFCXML, which would seem to be an ideal format for comparing changes on GitHub, and possibly also editing with native app support. Next version of IfcDoc (to be uploaded soon) generates IFCXML for properties and quantities according to the XSD configuration.

Here's the IFC2x3 export (without any translations):
https://github.com/BuildingSMART/IfcDoc/blob/master/IfcKit/schemas/IFC2X3_FINAL/templates.ifcxml

Here's the IFC4 Addendum 2 export (including translations):
https://raw.githubusercontent.com/BuildingSMART/IfcDoc/master/IfcKit/schemas/IFC4/templates.ifcxml

The way IFCXML is currently configured, it results in association relationships (including IfcRelAssociatesLibrary) being shown at root level, whereas it would seem more readable in most scenarios if such relationships were inline (as is done for various other relationships such as aggregation) -- so you would see translations directly under properties rather than at the end of the file. This would also result in smaller files, and more comparable files -- with translations inline, then object IDs wouldn't be necessary so you wouldn't see everything renumbered every time there's an addition/deletion. Another approach could be to simply move translations into separate IFCXML files (or use CSV files).

If there is to be an IFC4 Addendum 3, such change could go there -- and/or for IFC 4.1 Addendum 1 or IFC 4.2 (including new bridge definitions).

**Comment by klacol** [comment]
Great!

The file is based on the scheme IFC4/Add2TC1. Online I can download the scheme for IFC4/Add2. It would be optimal to base the file always on the published scheme.

I have some comments:

- When I change the scheme and validate the file; I get multiple validation errors
- Perhaps we should embed the IfcPropertySetTemplates into an IfcProjectLibrary and not into an IfcProject
- The header should be inserted

**Comment by klacol** [comment]
This is the way, we structure the template in CAFM-Connect:

https://github.com/CAFM-Connect/BIM-Profiles/blob/master/Catalogue%20files/CAFM-ConnectFacilitiesViewTemplate.ifcxml

**Comment by timchipman** [comment]
ifcXML header is now generated with latest checkin (and IfcDoc V12.0), and included with documentation.
